[package]
name = "arisaii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11"
toml = "0.5"
serde = { version = "1.0.*", features = ["derive"] }
anyhow = "*"
